language: python
python:
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh 
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  - conda config --prepend channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -n ci_env python=3.7 shapely rtree
  - source activate ci_env
  - pip install fiona
script:
# Remove file from previous execution
  - rm -f ./data/test_sherbend_out.gpkg
# Create the new file
  - pyhon sherbend.py -d 2.0 ./data/test_sherbend_in.gpkg ./data/test_sherbend_out.gpkg
# Validate that the content is equal to the standard file
  - python test_sherbend.py ./data/test_sherbend_out.gpkg ./data/test_sherbend_out_standard.gpkg 
